name: Deploy Vite Project to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write    # ✅ Permite o push automático para gh-pages
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
